### ISSUE TITLE
unable to push readme file 

### ISSUE THREAD

**Issue by dipyamandas2405** [30DaysofWebDEV/DSC-30-Days-of-Web#14]
tried pushing to master and main as was instructed to do ...
its showing 
error:src refspec main doed not match any 
pls help asap ...

**Comment by priteshkulshreshtha** [comment]
I assume you're doing the "git-task". If yes, this is not the repository you need to push to. Please make the PR in the "git-task" repo.

Find the same [here](https://github.com/30DaysofWebDEV/git-task).
